package rules;

import com.ftn.sbnz.backward.model.models.*;
import java.util.List
import java.util.HashSet
import java.util.ArrayList

//rule "create recommendation learning methods list based on field"
//when
//    $student: Student(learningMethodsUpdated2 == false,
//                      learningMethodsBasedOnTraits != null,
//                      learningMethodsBasedOnTraits.isEmpty() == false,
//                      learningMethodsBasedOnField != null,
//                      learningMethodsBasedOnField.isEmpty() == false)
//then
//    Set<LearningMethod> commonMethods = new HashSet<>( $student.getLearningMethodsBasedOnTraits() );
//    commonMethods.retainAll( $student.getLearningMethodsBasedOnField() );
//    List<LearningMethod> commons = new ArrayList<LearningMethod>(commonMethods);
//    modify($student) {
//        setLearningMethods(commons),
//        setLearningMethods2Updated(true);
//    }
//end

rule "Check All Traits for Student"
when
    $student : Student( $traits : personalityTraits )
then
    System.out.println("\nStudent has the following personality traits: " + $traits +"\n");
end

rule "Check All Learning Methods for Student"
when
    $student : Student( $methods : learningMethods )
then
    System.out.println("\nStudent's learning methods: " + $methods +"\n");
end

rule "Check All Subject Names for Student"
when
    $student : Student( $subjects : subjects )
then
    System.out.println("\nStudent's subjects: " + $subjects +"\n");
end


